### ISSUE TITLE
ImmsersiveView no longer centers

### ISSUE THREAD

**Issue by raidingsnow** [ohitstom/spicetify-extensions#21] opened 2024-08-02 08:15 UTC
Title pretty much. None of the top content such as playlist info + the playlist image does not show. The playlist name also doesn't center. I have tried installing it manually and through marketplace, no luck. I am also on Linux Fedora using the flatpak version of spotify if that helps.

**Comment by ohitstom** [comment] 2024-08-05 21:40
pictures of the issue, along with your spotify config (themes you are using, extensions, app versions etc)

**Comment by raidingsnow** [comment] 2024-08-06 23:25
![swappy-20240806_191124](https://github.com/user-attachments/assets/45279601-edff-4c71-8feb-c25fc9ba42ed)
![swappy-20240806_192313](https://github.com/user-attachments/assets/3569c4c7-0964-4c7c-ac60-113d60c17bee)
Here is my config and trying to use immersive view. I recently switched to arch and I am using the spotify-launcher version so I am only using the ImmersiveView extension,

**Comment by ohitstom** [comment] 2024-08-06 23:28
are you certain you have changed nothing else and have nothing else installed? could you try maybe messing around with your experimental features to see if any of those being toggled on or off fixes it.

running the same Spotify and spicetify version (barring the use of arch since I don't use Linux) I'm having no issues :/

**Comment by raidingsnow** [comment] 2024-08-07 01:43
I tried on my windows partition and it does work so I’ll just chalk this up to a Linux/arch issue. I’ll report back if I can find the solution

**Comment by ohitstom** [comment] 2024-11-26 15:57
> I tried on my windows partition and it does work so I’ll just chalk this up to a Linux/arch issue. I’ll report back if I can find the solution

Awesome, i'll close this as not planned for now but feel free to re-open it if you ever figure out the cause!

**Closed by ohitstom** 2024-11-26 15:57 UTC
